### ISSUE TITLE
n/a

### ISSUE THREAD

**Issue by Moter8** [bucaran/mu#1]
n/a

**Comment by bucaran** [comment]
At first sight you would think the terminal does not support [ANSI color](http://en.wikipedia.org/wiki/ANSI_escape_code#Colors) code escapes.

I need to check if the terminal supports colors and act upon accordingly.

```sh
if [ -t 1 ]; then # This is an interactive terminal
    ncolors=$(tput colors) # And it supports colors
      # apply colors escapes prefix/suffix
...
```

**Comment by bucaran** [comment]
![fishtape](https://cloud.githubusercontent.com/assets/8317250/11613543/30c17c3c-9c68-11e5-8432-d321b2296e0a.png)

:+1:

**Comment by bucaran** [comment]
![fishtape](https://cloud.githubusercontent.com/assets/8317250/11807722/07848e1a-a35f-11e5-8f38-a8860f249b77.png)

**Comment by bucaran** [comment]
![fishtape](https://cloud.githubusercontent.com/assets/8317250/11807851/f76839a4-a35f-11e5-9ed8-a77604fbd546.png)
